config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  get 'login', to:'users#login'
  get 'login_check',to:'users#login_check'
  post 'login_check', to: 'users#login_check'
  get 'logout', to: 'users#logout'
  resources :questions, except: [:show] do
    resources :answers ,shallow: true,except: [:edit,:update,:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    if not session[:current_user_id]
      redirect_to controller: 'questions',action: :index
    end
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @answer.question_id = params[:question_id]
    respond_to do |format|
      if @answer.save
        format.html { redirect_to controller: "questions",action: :index, notice: '成功提交回答！' }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @question = @answer.question
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_answers_path(@question), notice: '删除成功!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:username, :identifier, :phone, :content, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :except => :login_check
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :islogin? ,only: [:edit,:new,:update,:destroy]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = session[:current_user_id]
    respond_to do |format|
      if @question.save
        format.html { redirect_to controller: 'questions', action: :index , notice: 'Question was successfully created.' }
        format.json { render :index, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to action: :index, notice: '修改成功！' }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: '删除成功！' }
      format.json { head :no_content }
    end
  end

  private

    def islogin?
      if not session[:current_user_id]
        redirect_to controller: :users,action: :login
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :typename)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login_check
    if @user = password_check(params[:username],params[:password])
      session[:current_user_id] = @user.id
    end
  end

  def logout
    if session[:current_user_id]
      session.delete :current_user_id
    end
  end

  def login

  end
  private
    def password_check(username,password)
      @user = User.find_by_username username
      if @user and @user.password==password
        return @user
      else
        return false
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer,url:question_answers_path, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :"用户名" %>
    <%= form.text_field :username,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :"学号"%>
    <%= form.text_field :identifier,class:"form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :"电话"%>
    <%= form.text_field :phone ,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :"答案" %>
    <%= form.text_area :content ,class:"wysihtml5"%>
  </div>
  <div class="row">
    <div class="col-md-8">
    </div>
    <div class="col-md-2">
      <%= form.submit class:"btn btn-success" ,value:"提交"%>
    </div>
    <div class="col-md-2">
      <%= button_to '返回',  questions_path ,method: :get,class:"btn btn-success" %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function(){

        $('.wysihtml5').each(function(i, elem) {
            $(elem).wysihtml5();
        });

    })
</script>
<style type="text/css">
  iframe.wysihtml5-sandbox{
    width: 100% ! important;
  }
</style>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', question_answers_path(@answer) %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>
<h3>回答</h3>
<%=button_to "返回",questions_path,method: :get,class:"btn btn-success" %>
<% @answers.each do |answer| %>
  <h5>
    <%="姓名："+answer.username+"       学号："+answer.identifier+"       电话："+answer.phone%>
  </h5>
  <%=answer.content.to_s.html_safe%>
  <div class="row" id="buttons">
      <div class="col-md-11"></div>
      <div class="col-md-1">
        <%=button_to '删除', answer, method: :delete, data: { confirm: '确定删除么?' } ,class:"btn btn-success" %>
      </div>
  </div>

<%end %>

app/views/answers/new.html.erb
<h1>新回答</h1>

<%= render 'form', answer: @answer %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @answer.username %>
</p>

<p>
  <strong>Identifier:</strong>
  <%= @answer.identifier %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @answer.phone %>
</p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<%= link_to 'Back', questions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FAQ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
      <%= yield %>
      </div>
      <div class="col-md-3">
      </div>
    </div>
  </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :"标题" %>
    <%= form.text_field :title,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :"类型" %>
    <%= form.text_field :typename,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :"正文" %>
    <%= form.text_area :content,class:"wysihtml5" %>
  </div>

  <div class="row">
    <div class="col-md-1">
      <%= form.submit class:"btn btn-success" ,method: :put,value:"提交"%>
    </div>
    <div class="col-md-11">
    </div>
  </div>
<% end %>
<script type="text/javascript">
    $(document).ready(function(){

        $('.wysihtml5').each(function(i, elem) {
            $(elem).wysihtml5();
        });

    })
</script>
<style type="text/css">
  iframe.wysihtml5-sandbox{
    width: 100% ! important;
  }
</style>

app/views/questions/edit.html.erb
<h1>编辑问题</h1>

<%= render 'form', question: @question %>
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<%if session[:current_user_id] %>
  <%=button_to '创建新问题', new_question_path ,method: :get,class:"btn btn-success"%>
<%end %>
      <% @questions.each do |question| %>
      <h3 class="text-center">
        <%=question.title %>
      </h3>
	  <%question.content.split(/<br>/).each do |str|%>
		  <p><%=str%><p/>
	  <%end%>
      <div class="row" id="buttons">
        <%if session[:current_user_id] %>
            <div class="col-md-9"></div>
            <div class="col-md-1">
            <%=button_to '回答', question_answers_path(question),method: :get, class:"btn btn-success"%>
            </div>
            <div class="col-md-1">
            <%= button_to '编辑', edit_question_path(question) ,method: :get,class:"btn btn-success"%>
            </div>
            <div class="col-md-1">
            <%= button_to '删除', question, method: :delete, data: { confirm: '确定删除么？' }, class:"btn btn-success"%>
            </div>
        <%else %>
          <%= button_to '回答', new_question_answer_path(question) ,method: :get,class:"btn btn-success"%>
        <%end %>
      </div>

<%end %>

app/views/questions/new.html.erb
<h1>新建问题</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>标题:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>内容:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>类型:</strong>
  <%= @question.typename %>
</p>
<%if session[:current_user_id] %>
<%= link_to '编辑', edit_question_path(@question) %> |
<%else%>
  <td><%= link_to '回答', new_answer_path(question) %></td>
<%end%>
<%= link_to '返回', questions_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username%></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/login.html.erb
<h3>登录</h3>
<script type="text/javascript">
  function login() {
      $.ajax({
          //几个参数需要注意一下
          type: "POST",//方法类型
          dataType: "json",//预期服务器返回的数据类型
          url: "/login_check" ,//url
          data: $('#loginForm').serialize(),
          success: function (result) {
              console.log(result);//打印服务端返回的数据(调试用)
              if (result.status == true) {
                  window.location.href="/questions";
              }else
              {
                  alert("用户名或密码错误");
              }
              ;
          },
          error : function() {
              alert("异常！");
          }
      });
  }
</script>
<div id="form-div">
  <form id="loginForm" onsubmit="false" action="##" method="post" role="form" >
    <div class="form-group">
      <label>
        用户名:
      </label>
      <input name="username" type="text" class="form-control"/>
    </div>
    <div class="form-group">
     <label>
       密码:
     </label>
      <input name="password" type="password" class="form-control"/>
    </div>
    <div class="form-group">
      <input type="button" class="btn btn-success" value="登录" onclick="login()"/></p>
    </div>
  </form>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>用户名:<%=@user.username %></p>
<p>创建时间:<%=@user.created_at%></p>
<p>更新时间:<%=@user.updated_at%></p>
<%= link_to '返回', users_path %>